import os
import numpy as np
import matplotlib.pyplot as plt

# Create output directory
output_dir = './output'
os.makedirs(output_dir, exist_ok=True)

# ==========================================
# PHYSICAL CONSTANTS & INITIAL QUANTITIES
# ==========================================
# Standard values defined in the study:
g = 9.81          # Acceleration due to gravity (m/s^2)
mu_s = 0.2        # Coefficient of sliding friction (Felt/Ball)
mu_r = 0.015      # Coefficient of rolling resistance
R = 0.0285        # Standard ball radius (meters) ~ 57.15 mm diameter
M = 0.170         # Standard ball mass (kg) ~ 170 grams
INERTIA = (2 / 5) * M * (R ** 2)  # Moment of Inertia for a solid sphere

# ==========================================
# 1. SLIDING TO ROLLING: VELOCITY KINEMATICS
# ==========================================
def plot_sliding_to_rolling_velocity():
    """
    Description for the Study:
    --------------------------
    Figure 1: Kinematic velocity profiles during the transition from sliding to pure rolling.
    The graph tracks the simultaneous linear velocity decay ($dv/dt = -\mu_s g$) and angular velocity
    acceleration ($d\omega/dt = \mu_s M g R / I$) generated by kinetic cloth friction. The sliding mechanics
    cease at $t_{co} = {t_co:.3f}\text{ s}$ when the perimeter velocity equals the center-of-mass translation
    ($v = R \cdot \omega$), yielding a transition into the highly efficient rolling phase where velocity
    stabilizes under minimal rolling resistance ($\mu_r$).
    """
    v0 = 4.0
    t_co = (2 * v0) / (7 * mu_s * g)
    v_co = (5 / 7) * v0

    t_sliding = np.linspace(0, t_co, 500)
    t_rolling = np.linspace(t_co, t_co + 1.5, 500)
    t_full = np.concatenate([t_sliding, t_rolling])

    v_slide = v0 - mu_s * g * t_sliding
    w_slide = (mu_s * M * g * R / INERTIA) * t_sliding

    v_roll = v_co - mu_r * g * (t_rolling - t_co)
    w_roll = v_roll / R

    v_total = np.concatenate([v_slide, v_roll])
    w_total = np.concatenate([w_slide, w_roll])

    fig, ax1 = plt.subplots(figsize=(10, 5))
    color = 'tab:blue'
    ax1.set_xlabel('Time (seconds)', fontsize=12)
    ax1.set_ylabel('Linear Velocity v (m/s)', color=color, fontsize=12)
    ax1.plot(t_full, v_total, color=color, linewidth=2.5, label='Linear Velocity ($v$)')
    ax1.tick_params(axis='y', labelcolor=color)
    ax1.grid(True, linestyle='--', alpha=0.6)

    ax2 = ax1.twinx()
    color = 'tab:orange'
    ax2.set_ylabel('Angular Velocity $\omega$ (rad/s)', color=color, fontsize=12)
    ax2.plot(t_full, w_total, color=color, linewidth=2.5, linestyle='--', label='Angular Velocity ($\omega$)')
    ax2.tick_params(axis='y', labelcolor=color)

    plt.axvline(x=t_co, color='red', linestyle=':', alpha=0.8, linewidth=2)
    plt.title('Figure 1: Velocity Transitions (Sliding Phase to Rolling Phase)', fontsize=14, pad=15)
    fig.tight_layout()
    plt.savefig(f'{output_dir}/chart1_sliding_to_rolling_velocity.png')

# ==========================================
# 2. SPIN DECAY VARIATIONS (MULTIPLE DEGREES)
# ==========================================
def plot_spin_decay_curves():
    """
    Description for the Study:
    --------------------------
    Figure 2: Time-resolved spin decay profiles mapping the dissipation of angular velocity ($\omega$)
    across four distinct initial angular spin application intensities ($\omega_0 = 15, 30, 45, 60\text{ rad/s}$).
    The progressive curves capture the torque decay exerted by table cloth fibers. High initial spin rates
    maintain long-term rotational kinetic energy, revealing how macro-spin quantities outlast sliding frictional transitions
    before settling into steady micro-decay patterns controlled by rolling frictional interactions.
    """
    time = np.linspace(0, 3.0, 1000)
    initial_spins = [15, 30, 45, 60]
    colors = ['green', 'blue', 'orange', 'crimson']

    plt.figure(figsize=(10, 5))
    for w0, color in zip(initial_spins, colors):
        decay_constant = 0.45
        w_t = w0 * np.exp(-decay_constant * time) - (mu_r * g / R) * time
        w_t = np.clip(w_t, 0, None)
        plt.plot(time, w_t, color=color, linewidth=2.2, label=f'$\omega_0$ = {w0} rad/s')

    plt.xlabel('Time (seconds)', fontsize=12)
    plt.ylabel(r'Angular Velocity $\omega$ (rad/s)', fontsize=12)
    plt.title('Figure 2: Spin Decay Profiles across Multiple Spin Intensities', fontsize=14, pad=15)
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.legend(title='Initial Spin Degrees', loc='upper right')
    plt.tight_layout()
    plt.savefig(f'{output_dir}/chart2_spin_decay_curves.png')

# ==========================================
# 3. CUSHION INTERACTIONS WITH VARIED SPIN
# ==========================================
def plot_cushion_spin_states():
    """
    Description for the Study:
    --------------------------
    Figure 3: Non-linear angular deflection tracking of cushion reflections under varying spin conditions
    (Top Spin, Back Spin, No Spin, and Ideal Specular Reflection). Ideal reflection mirrors a perfect
    symmetrical path ($\alpha_i = \alpha_r$). In contrast, top spin applies an accelerated force vector parallel
    to the cushion wall, compressing the reflection angle ($\alpha_r$) and expanding the rebound path width.
    Back spin generates opposing friction against the cushion surface, retarding parallel displacement to produce
    sharper, highly narrow rebound exit angles.
    """
    alpha_incident_deg = np.linspace(15, 75, 100)
    alpha_incident_rad = np.radians(alpha_incident_deg)
    e_c = 0.85 # Restitution coefficient

    tan_no_spin = np.tan(alpha_incident_rad) / e_c
    tan_top_spin = (np.tan(alpha_incident_rad) * 1.35) / e_c
    tan_back_spin = (np.tan(alpha_incident_rad) * 0.65) / e_c

    alpha_no_spin = np.degrees(np.arctan(tan_no_spin))
    alpha_top_spin = np.degrees(np.arctan(tan_top_spin))
    alpha_back_spin = np.degrees(np.arctan(tan_back_spin))

    plt.figure(figsize=(10, 6))
    plt.plot(alpha_incident_deg, alpha_incident_deg, color='black', linestyle=':', linewidth=2, label='Ideal Reflection (Specular)')
    plt.plot(alpha_incident_deg, alpha_no_spin, color='blue', linewidth=2.5, label='Natural Rebound (No Spin)')
    plt.plot(alpha_incident_deg, alpha_top_spin, color='green', linewidth=2.5, linestyle='--', label='Top Spin Rebound')
    plt.plot(alpha_incident_deg, alpha_back_spin, color='crimson', linewidth=2.5, linestyle='-.', label='Back Spin Rebound')

    plt.xlabel(r'Incident Angle $\alpha_i$ (Degrees from Normal)', fontsize=12)
    plt.ylabel(r'Reflection Angle $\alpha_r$ (Degrees from Normal)', fontsize=12)
    plt.title('Figure 3: Cushion Impact Angles under Distinct Spin Variants', fontsize=14, pad=15)
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.legend(loc='upper left', fontsize=10)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/chart3_cushion_spin_states.png')

# ==========================================
# 4. CUSHION INTERACTION REGIMES (STICKY VS NON-STICKY)
# ==========================================
def plot_cushion_friction_regimes():
    """
    Description for the Study:
    --------------------------
    Figure 4: Comparative evaluation of cushion impact mechanics under Sticky and Non-Sticky friction regimes.
    The Non-Sticky regime assumes continuous relative sliding along the cushion length across the micro-duration
    of the impact, yielding smooth, predictive behavior. The Sticky regime maps a grip-lock phenomenon where
    tangential relative speed reaches zero mid-impact, forcing a momentary transition to localized rolling along the
    cushion profile before release. This results in distinct trajectory inflections at shallow incident configurations.
    """
    alpha_incident_deg = np.linspace(10, 80, 100)
    alpha_incident_rad = np.radians(alpha_incident_deg)
    e_c = 0.85

    alpha_non_sticky_deg = np.degrees(np.arctan(np.tan(alpha_incident_rad) / e_c))
    sticky_factor = 1.0 + 0.4 * np.sin(alpha_incident_rad)**2
    alpha_sticky_deg = np.degrees(np.arctan((np.tan(alpha_incident_rad) / e_c) * sticky_factor))

    plt.figure(figsize=(10, 6))
    plt.plot(alpha_incident_deg, alpha_non_sticky_deg, color='teal', linewidth=2.5, label='Non-Sticky Regime (Continuous Sliding)')
    plt.plot(alpha_incident_deg, alpha_sticky_deg, color='darkred', linewidth=2.5, linestyle='--', label='Sticky Regime (Grip-Lock Transition)')
    plt.plot(alpha_incident_deg, alpha_incident_deg, color='gray', linestyle=':', alpha=0.6, label='Reference Standard Axis')

    plt.xlabel(r'Incident Angle $\alpha_i$ (Degrees from Normal)', fontsize=12)
    plt.ylabel(r'Reflection Angle $\alpha_r$ (Degrees from Normal)', fontsize=12)
    plt.title('Figure 4: Cushion Dynamics - Sticky vs. Non-Sticky Friction Regimes', fontsize=14, pad=15)
    plt.grid(True, linestyle='--', alpha=0.5)
    plt.legend(loc='upper left', fontsize=10)
    plt.tight_layout()
    plt.savefig(f'{output_dir}/chart4_cushion_friction_regimes.png')

# ==========================================
# EXECUTION CONTROLLER
# ==========================================
if __name__ == "__main__":
    plot_sliding_to_rolling_velocity()
    plot_spin_decay_curves()
    plot_cushion_spin_states()
    plot_cushion_friction_regimes()
