import { BALL_RADIUS, CUSHION_ANGLE, SIN_CUSHION, COS_CUSHION } from "../physics/constants"

export { BALL_RADIUS, CUSHION_ANGLE, SIN_CUSHION, COS_CUSHION }
export const CUE_TIP_OFFSET = 0.690
export const CONTACT_RADIUS = BALL_RADIUS / 2
